/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2016-10-09 09:54:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webapp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profileDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>User profile form requirement</title>\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\" integrity=\"sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <!--     <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            padding-top: 70px;\r\n");
      out.write("            /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .othertop{margin-top:10px;}\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"../resources/styles/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- [endif] -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\"></div><br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar -->\r\n");
      out.write("<div id=\"sidebar-wrapper\">\r\n");
      out.write("    <ul class=\"sidebar-nav\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href = \"profileDetails.jsp\">Basic details</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href = \"EmergencyContact.html\">Emergency Contact</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href = \"exceptionalities.html\">Exceptionalities</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"interests.html\">Interests</a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-10 \">\r\n");
      out.write("            <form class=\"form-horizontal\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Text input-->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Name (Full name)\">Name (Full name)</label>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <div class=\"input-group-addon\">\r\n");
      out.write("                                    <i class=\"fa fa-user\">\r\n");
      out.write("                                    </i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input id=\"Name (Full name)\" name=\"Name (Full name)\" type=\"text\" placeholder=\"Name (Full name)\" class=\"form-control input-md\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- File Button -->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Upload photo\">Upload photo</label>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <input id=\"Upload photo\" name=\"Upload photo\" class=\"input-file\" type=\"file\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Text input-->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Date Of Birth\">Date Of Birth</label>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <div class=\"input-group-addon\">\r\n");
      out.write("                                    <i class=\"fa fa-birthday-cake\"></i>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input id=\"Date Of Birth\" name=\"Date Of Birth\" type=\"text\" placeholder=\"Date Of Birth\" class=\"form-control input-md\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Text input-->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Mother\">Mother's Name</label>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <div class=\"input-group-addon\">\r\n");
      out.write("                                    <i class=\"fa fa-female\" style=\"font-size: 20px;\"></i>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input id=\"Mother\" name=\"Mother\" type=\"text\" placeholder=\"Mother's Name\" class=\"form-control input-md\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Multiple Radios (inline) -->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Gender\">Gender</label>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label class=\"radio-inline\" for=\"Gender-0\">\r\n");
      out.write("                                <input type=\"radio\" name=\"Gender\" id=\"Gender-0\" value=\"1\" checked=\"checked\">\r\n");
      out.write("                                Male\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"radio-inline\" for=\"Gender-1\">\r\n");
      out.write("                                <input type=\"radio\" name=\"Gender\" id=\"Gender-1\" value=\"2\">\r\n");
      out.write("                                Female\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"radio-inline\" for=\"Gender-2\">\r\n");
      out.write("                                <input type=\"radio\" name=\"Gender\" id=\"Gender-2\" value=\"3\">\r\n");
      out.write("                                Other\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label col-xs-12\" for=\"Permanent Address\">Permanent Address</label>\r\n");
      out.write("                        <div class=\"col-md-2  col-xs-4\">\r\n");
      out.write("                            <input id=\"Address\" name=\"Address\" type=\"text\" placeholder=\"District\" class=\"form-control input-md \">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-2 col-xs-4\">\r\n");
      out.write("\r\n");
      out.write("                            <input id=\"Address\" name=\"Address\" type=\"text\" placeholder=\"Area\" class=\"form-control input-md \">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Permanent Address\"></label>\r\n");
      out.write("                        <div class=\"col-md-2  col-xs-4\">\r\n");
      out.write("                            <input id=\"Address\" name=\"Permanent Address\" type=\"text\" placeholder=\"Street\" class=\"form-control input-md \">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Text input-->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Phone number \">Phone number </label>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <div class=\"input-group-addon\">\r\n");
      out.write("                                    <i class=\"fa fa-phone\"></i>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input id=\"Phone number \" name=\"Phone number \" type=\"text\" placeholder=\"Primary Phone number \" class=\"form-control input-md\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group othertop\">\r\n");
      out.write("                                <div class=\"input-group-addon\">\r\n");
      out.write("                                    <i class=\"fa fa-mobile fa-1x\" style=\"font-size: 20px;\"></i>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input id=\"Phone number \" name=\"Secondary Phone number \" type=\"text\" placeholder=\" Secondary Phone number \" class=\"form-control input-md\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Text input-->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-4 control-label\" for=\"Email Address\">Email Address</label>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <div class=\"input-group-addon\">\r\n");
      out.write("                                    <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input id=\"Email Address\" name=\"Email Address\" type=\"text\" placeholder=\"Email Address\" class=\"form-control input-md\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-2 hidden-xs\">\r\n");
      out.write("            <img src=\"http://websamplenow.com/30/userprofile/images/avatar.jpg\" class=\"img-responsive img-thumbnail \">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- jQuery Version 1.11.1 -->\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
