/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2016-10-09 09:10:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webapp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Case</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!-- jQuery Version 1.11.1 -->\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write(" <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\" integrity=\"sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <!--     <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"../resources/styles/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            $(\".btn-pref .btn\").click(function () {\r\n");
      out.write("                $(\".btn-pref .btn\").removeClass(\"btn-primary\").addClass(\"btn-default\");\r\n");
      out.write("                // $(\".tab\").addClass(\"active\"); // instead of this do the below\r\n");
      out.write("                $(this).removeClass(\"btn-default\").addClass(\"btn-primary\");\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <link rel = \"stylesheet\" href = \"../resources/styles/cards.css\"/>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("\t  $(\".btn-pref .btn\").click(function () {\r\n");
      out.write("\t      $(\".btn-pref .btn\").removeClass(\"btn-primary\").addClass(\"btn-default\");\r\n");
      out.write("\t      // $(\".tab\").addClass(\"active\"); // instead of this do the below \r\n");
      out.write("\t      $(this).removeClass(\"btn-default\").addClass(\"btn-primary\");   \r\n");
      out.write("\t  });\r\n");
      out.write("\t  });\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <style>\r\n");
      out.write("  .trash { color:rgb(209, 91, 71); }\r\n");
      out.write(".flag { color:rgb(248, 148, 6); }\r\n");
      out.write(".panel-body { padding:0px; }\r\n");
      out.write(".panel-footer .pagination { margin: 0; }\r\n");
      out.write(".panel .glyphicon,.list-group-item .glyphicon { margin-right:5px; }\r\n");
      out.write(".panel-body .radio, .checkbox { display:inline-block;margin:0px; }\r\n");
      out.write(".panel-body input[type=checkbox]:checked + label { text-decoration: line-through;color: rgb(128, 144, 160); }\r\n");
      out.write(".list-group-item:hover, a.list-group-item:focus {text-decoration: none;background-color: rgb(245, 245, 245);}\r\n");
      out.write(".list-group { margin-bottom:0px; }\r\n");
      out.write("  .card {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    background-color: rgba(214, 224, 226, 0.2);\r\n");
      out.write("    -webkit-border-top-left-radius:5px;\r\n");
      out.write("    -moz-border-top-left-radius:5px;\r\n");
      out.write("    border-top-left-radius:5px;\r\n");
      out.write("    -webkit-border-top-right-radius:5px;\r\n");
      out.write("    -moz-border-top-right-radius:5px;\r\n");
      out.write("    border-top-right-radius:5px;\r\n");
      out.write("    -webkit-box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding-top: 0;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    background-color: rgba(255, 255, 255, 1);\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard .card-background {\r\n");
      out.write("    height: 130px;\r\n");
      out.write("}\r\n");
      out.write(".card-background img {\r\n");
      out.write("    -webkit-filter: blur(25px);\r\n");
      out.write("    -moz-filter: blur(25px);\r\n");
      out.write("    -o-filter: blur(25px);\r\n");
      out.write("    -ms-filter: blur(25px);\r\n");
      out.write("    filter: blur(25px);\r\n");
      out.write("    margin-left: -100px;\r\n");
      out.write("    margin-top: -200px;\r\n");
      out.write("    min-width: 130%;\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard .useravatar {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 15px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard .useravatar img {\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    max-width: 100px;\r\n");
      out.write("    max-height: 100px;\r\n");
      out.write("    -webkit-border-radius: 50%;\r\n");
      out.write("    -moz-border-radius: 50%;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    border: 5px solid rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard .card-info {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 14px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard .card-info .card-title {\r\n");
      out.write("    padding:0 5px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    line-height: 1;\r\n");
      out.write("    color: #262626;\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.1);\r\n");
      out.write("    -webkit-border-radius: 4px;\r\n");
      out.write("    -moz-border-radius: 4px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard .card-info {\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("    color: #737373;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write(".card.hovercard .bottom {\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("    margin-bottom: 17px;\r\n");
      out.write("}\r\n");
      out.write(".btn-pref .btn {\r\n");
      out.write("    -webkit-border-radius:0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"col-lg-6 col-sm-6\" style=\"width:100%;\">\r\n");
      out.write("    <div class=\"btn-pref btn-group btn-group-justified btn-group-lg\"  group\" aria-label=\"...\">\r\n");
      out.write("        <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("            <button type=\"button\" id=\"stars\" class=\"btn btn-primary\" href=\"#tab1\" data-toggle=\"tab\"><span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <div>Home</div>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("            <button type=\"button\" id=\"favorites\" class=\"btn btn-default\" href=\"#tab2\" data-toggle=\"tab\"><span class=\"glyphicon glyphicon-heart\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <div>Profile</div>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("            <button type=\"button\" id=\"following\" class=\"btn btn-default\" href=\"#tab3\" data-toggle=\"tab\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <div>Sponsored Challenges</div>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"well\">\r\n");
      out.write("      <div class=\"tab-content\">\r\n");
      out.write("        <div class=\"tab-pane fade in active\" id=\"tab1\">\r\n");
      out.write("          <h3>Wall</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tab-pane fade in\" id=\"tab2\">\r\n");
      out.write("        \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "profileDetails.jsp", out, false);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"tab-pane fade in\" id=\"tab3\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("            <div class=\"panel panel-primary\">\r\n");
      out.write("                <div class=\"panel-heading\">\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-list\"></span>Available Challenges\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"panel-body\">\r\n");
      out.write("                    <ul class=\"list-group\">\r\n");
      out.write("                        <li class=\"list-group-item\">\r\n");
      out.write("                               <a href=\"details.jsp\"><span>Photography Challenge</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--<div class=\"panel-footer\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <h6>\r\n");
      out.write("                                Total Count <span class=\"label label-info\">25</span></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <ul class=\"pagination pagination-sm pull-right\">\r\n");
      out.write("                                <li class=\"disabled\"><a href=\"javascript:void(0)\">«</a></li>\r\n");
      out.write("                                <li class=\"active\"><a href=\"javascript:void(0)\">1 <span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">2</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">3</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">4</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">5</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:void(0)\">»</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
