/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2016-10-09 06:49:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class challenges_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head><title>Bootstrap Case</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>.trash { color:rgb(209, 91, 71); }\r\n");
      out.write(".flag { color:rgb(248, 148, 6); }\r\n");
      out.write(".panel-body { padding:0px; }\r\n");
      out.write(".panel-footer .pagination { margin: 0; }\r\n");
      out.write(".panel .glyphicon,.list-group-item .glyphicon { margin-right:5px; }\r\n");
      out.write(".panel-body .radio, .checkbox { display:inline-block;margin:0px; }\r\n");
      out.write(".panel-body input[type=checkbox]:checked + label { text-decoration: line-through;color: rgb(128, 144, 160); }\r\n");
      out.write(".list-group-item:hover, a.list-group-item:focus {text-decoration: none;background-color: rgb(245, 245, 245);}\r\n");
      out.write(".list-group { margin-bottom:0px; }</style></head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("            <div class=\"panel panel-primary\">\r\n");
      out.write("                <div class=\"panel-heading\">\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-list\"></span>Sortable Lists\r\n");
      out.write("                    <div class=\"pull-right action-buttons\">\r\n");
      out.write("                        <div class=\"btn-group pull-right\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-default btn-xs dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <span class=\"glyphicon glyphicon-cog\" style=\"margin-right: 0px;\"></span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <ul class=\"dropdown-menu slidedown\">\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-pencil\"></span>Edit</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-trash\"></span>Delete</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-flag\"></span>Flag</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"panel-body\">\r\n");
      out.write("                    <ul class=\"list-group\">\r\n");
      out.write("                        <li class=\"list-group-item\">\r\n");
      out.write("                            <div class=\"checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"checkbox\" />\r\n");
      out.write("                                <label for=\"checkbox\">\r\n");
      out.write("                                    List group item heading\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pull-right action-buttons\">\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-pencil\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"trash\"><span class=\"glyphicon glyphicon-trash\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"flag\"><span class=\"glyphicon glyphicon-flag\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-group-item\">\r\n");
      out.write("                            <div class=\"checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"checkbox2\" />\r\n");
      out.write("                                <label for=\"checkbox2\">\r\n");
      out.write("                                    List group item heading 1\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           <div class=\"pull-right action-buttons\">\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-pencil\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"trash\"><span class=\"glyphicon glyphicon-trash\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"flag\"><span class=\"glyphicon glyphicon-flag\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-group-item\">\r\n");
      out.write("                            <div class=\"checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"checkbox3\" />\r\n");
      out.write("                                <label for=\"checkbox3\">\r\n");
      out.write("                                    List group item heading 2\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pull-right action-buttons\">\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-pencil\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"trash\"><span class=\"glyphicon glyphicon-trash\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"flag\"><span class=\"glyphicon glyphicon-flag\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-group-item\">\r\n");
      out.write("                            <div class=\"checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"checkbox4\" />\r\n");
      out.write("                                <label for=\"checkbox4\">\r\n");
      out.write("                                    List group item heading 3\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pull-right action-buttons\">\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-pencil\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"trash\"><span class=\"glyphicon glyphicon-trash\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"flag\"><span class=\"glyphicon glyphicon-flag\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-group-item\">\r\n");
      out.write("                            <div class=\"checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"checkbox5\" />\r\n");
      out.write("                                <label for=\"checkbox5\">\r\n");
      out.write("                                    List group item heading 4\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           <div class=\"pull-right action-buttons\">\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\"><span class=\"glyphicon glyphicon-pencil\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"trash\"><span class=\"glyphicon glyphicon-trash\"></span></a>\r\n");
      out.write("                                <a href=\"http://www.jquery2dotnet.com\" class=\"flag\"><span class=\"glyphicon glyphicon-flag\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"panel-footer\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <h6>\r\n");
      out.write("                                Total Count <span class=\"label label-info\">25</span></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <ul class=\"pagination pagination-sm pull-right\">\r\n");
      out.write("                                <li class=\"disabled\"><a href=\"javascript:void(0)\">«</a></li>\r\n");
      out.write("                                <li class=\"active\"><a href=\"javascript:void(0)\">1 <span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">2</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">3</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">4</a></li>\r\n");
      out.write("                                <li><a href=\"http://www.jquery2dotnet.com\">5</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:void(0)\">»</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
