/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2016-10-09 06:15:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Case</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h2>Welcome to Communitize</h2>\r\n");
      out.write("  <ul class=\"nav nav-tabs\">\r\n");
      out.write("    <li class=\"active\"><a data-toggle=\"tab\" href=\"#about-us\">About Us</a></li>\r\n");
      out.write("    <li><a data-toggle=\"tab\" href=\"#profile\">Profile</a></li>\r\n");
      out.write("    <li><a data-toggle=\"tab\" href=\"#stories\">Shared Stories</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"tab-content\">\r\n");
      out.write("    <div id=\"about-us\" class=\"tab-pane fade in active\">\r\n");
      out.write("      <h3>About Us</h3>\r\n");
      out.write("      <p>An application to bridge the gap between different kinds of people.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"profile\" class=\"tab-pane fade\">\r\n");
      out.write("      <h3>About Me</h3>\r\n");
      out.write("      <form action=\"survey\" name=\"survey-form\" method = \"POST\">\r\n");
      out.write("<table>\r\n");
      out.write("<tr>Contact</tr>\r\n");
      out.write("<tr><input type = \"text\" name=\"contact\"></tr></br>\r\n");
      out.write("<tr>Interests</tr></br>\r\n");
      out.write("<tr><textarea rows=3 name=\"interests\"></textarea></tr></br>\r\n");
      out.write("<tr>Favorite subject</tr></br>\r\n");
      out.write("<tr><input type=\"checkbox\" name=\"subject\" value=\"Math\"/>Math</tr></br>\r\n");
      out.write("<tr><input type=\"checkbox\" name=\"subject\" value=\"English\"/>English</tr></br>\r\n");
      out.write("<tr><input type=\"checkbox\" name=\"subject\" value=\"Science\"/>Science</tr></br>\r\n");
      out.write("<tr>Do you identify yourself with any of the following exceptionalities?</tr></br>\r\n");
      out.write("<tr><input type=\"checkbox\" name=\"disability\" value=\"Autism\"/>Math</tr></br>\r\n");
      out.write("<tr><input type=\"checkbox\" name=\"disability\" value=\"Dyslexia\"/>English</tr></br>\r\n");
      out.write("<tr><input type=\"checkbox\" name=\"disability\" value=\"Other\"/>Science</tr></br>\r\n");
      out.write("</br>\r\n");
      out.write("<tr>Do you want to make the above information public?</tr></br>\r\n");
      out.write("<tr><input type = \"radio\" name=\"consent\" value=\"0\"/>Yes</tr></br>\r\n");
      out.write("<tr><input type = \"radio\" name=\"consent\" value=\"1\"/>No</tr></br></br>\r\n");
      out.write("<tr><input type=\"submit\" value=\"Update\"/>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"stories\" class=\"tab-pane fade\">\r\n");
      out.write("      <h3>Shared Stories</h3>\r\n");
      out.write("      <p>Great Experience!</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
